name: Feature Request
description: Suggest a new feature or improvement
title: "[Feature] "
labels: ["type:enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature.
  - type: textarea
    id: problem
    attributes:
      label: Problem / motivation
      description: What problem does this solve or what need does it address?
      placeholder: "e.g. Every time I … I find it frustrating because … It would help if …"
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution / feature
      placeholder: Describe the behavior, API, or UI you have in mind.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      placeholder: Any other approaches, libraries, or workarounds you've considered.
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      placeholder: Screenshots, mockups, or related issues.
